### ISSUE TITLE
Offline use

### ISSUE THREAD

**Issue by ktjaco** [pelias/scripts-batch-search#1]
Is this batch geocoding search only restricted to online use? Would I be able to use my offline Pelias instance without an API key?

**Comment by orangejulius** [comment]
Hey @curiousc0w,
This particular script looks to have the URL for Mapzen Search [hardcoded](https://github.com/pelias/scripts-batch-search/blob/master/src/searchStream.js#L26), but it could easily be changed to point to a local URL if you've set up your own Pelias install locally. Without further modification of the script, you'd still have to specify an API key, but it could be anything, as there won't be any checking of the actual key.

Does that work for you? How else can we help?
